# ---

# name: CD

# on:
#   workflow_call:
 
# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - name: checkout-code
#         uses: actions/checkout@v7

#       - name: Copy Example Env to main env
#         run: cp .env.example .env 

#       - name: Login to Docker Hub
#         uses: docker/login-action@v4
#         with:
#           username: ${{ vars.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}  

#       - name: Run Docker Compose
#         run: |
#           docker compose pull
#           docker compose up -d --build     