---
# Goal is the run end to end DevSecOps Pipeline

name: DevSecOps

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  # Code Stage
  Code-Quality:
    uses: ./.github/workflows/code-quality.yaml
  
  # Secret Scan
  Secret-Scan:
    uses: ./.github/workflows/secret-scanning.yaml
    

  Dependency-Scanner:
    uses: ./.github/workflows/dependency-scan.yaml

  Docker-Scan:
    uses: ./.github/workflows/docker-scans.yaml
    secrets: inherit