---
# Goal is the run end to end DevSecOps Pipeline

name: DevSecOps.yaml

on:
  push:
    branches: [main]

jobs:
  # Code Stage
  code-quality:
    uses: ./.github/workflows/code-quality.yaml
  
  # Secret Scan
  secret-scaning:
    uses: ./.github/workflows/secret-scanning.yaml
    