---
# Goal- Ensure the docker files and docker images are security tested

name: Docker-Scan

on:
  workflow_call:

jobs:
  dockerlint-scan:
    runs-on: ubuntu-latest
    permissions:
      # contents permission to clone the repository
      contents: read
      packages: read
    strategy:
        matrix:
          folders: [backend, frontend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: ${{ matrix.folders }}-Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./${{ matrix.folders }}/Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   

      - name: docker build ${{ matrix.folders }}  
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folders }}:latest .
        working-directory: ./${{ matrix.folders }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folders }}:latest
          format: 'table'
          exit-code: '1'
          severity: 'HIGH'
          ignore-unfixed: true
          vuln-type: 'os,library'
      
      - name: Run Snyk to check Docker images for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folders }}:latest
          args: --severity-threshold=high    
          

      # - name: Super-linter for ${{ matrix.folders }}
      #   uses: super-linter/super-linter@v8.7.0 # x-release-please-version
      #   env:
      #     # To report GitHub Actions status checks
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

           